### ISSUE TITLE
add a Version command

### ISSUE THREAD

**Issue by nimakaviani** [cnoe-io/idpbuilder#108]
Right now, when tracking issues with idpBuilder, it is hard to reason about what version of the tool is used by the users.

It would be helpful for an `idpbuilder version` command to be added that corresponds to the released version of the idpbuilder.

Also, running `make build` in the terminal, should add a suffix to the version, indicating a local build, while `make build` in the CI and as part of the release cycle, should bump the version and remove any suffix from it, indicating a clean ready to release build of the tool

**Comment by hodgiwabi** [comment]
Please see #146 and let me know if that's what you're hoping for!
