### ISSUE TITLE
Populate gitea credentials for use with local git client

### ISSUE THREAD

**Issue by nimakaviani** [cnoe-io/idpbuilder#111]
we need to add a command to allow users to interact with gitea from their local dev environments. This is helpful for testing and development purposes, particularly after the conversation in #107. 

In #107 we settled on delegating to Gitea and Argo CD to manage the development and reconciliation of local custom packages. this requires for users to have an easy way to push go Gitea.

The following command (open to suggestions):
```
idpbuilder config gitea --save
```

should populate the local git credentials with gitea configuration so that users can use the local git client to push to gitea.

The configuration should skip `sslVerify` and potentially set up `cache --timeout=<timeout>` for the credentials to be kept in memory and deleted after certain amount of time, without altering users' `gitconfig` on the disk.

**Comment by cmoulliard** [comment]
> The following command (open to suggestions):

`idpbuilder config gitea` is enough. Why do you appended `--save` ?

**Comment by cmoulliard** [comment]
> should populate the local git credentials with gitea configuration so that users can use the local git client to push to gitea.

I think that we should develop a bit more what we want to do here as we are talking about 2 types of users: admin and lambda user. 

This command `idpbuilder config gitea` should return the url of the endpoint and admin username & password

To be able to support what you suggest here `should populate the local git credentials with gitea configuration so that users can use the local git client to push to gitea` then another command will be needed to able to create a user like gitea CLI can do `gitea admin user create --username myname --password asecurepassword --email me@example.com` but using REST API

```
idpbuilder create --package gitea --username myname --password asecurepassword --email me@example.com
```
**Remark**: To be able to push to the git repository, then SSH Key be needed too ;-)

@nimakaviani

**Comment by nimakaviani** [comment]
we still need to define the actual user stories around these, but what I am thinking right now is

```bash
$ idpbuilder config
# pretty prints configuration details for all endpoints

$ idpbuilder config -o json
# prints configuration details for all endpoints in json
```

```json
{
  "argocd": {
    "url": "https://argocd.cnoe.localtest.me:8433",
    "username": "USERNAME",
    "password": "PASSWORD"
  },
  "gitea": {
    "url": "https://gitea.cnoe.localtest.me:8443",
    "username": "USERNAME",
    "password": "PASSWORD"
  },
  "backstage": {
    "url": "https://backstage.cnoe.localtest.me:8443",
    "username": "USERNAME",
    "password": "PASSWORD"
  }
}
```

specially given that the core set of idp tools are going to be small (Argo CD, Gitea, Backstage), a complete json list is probably very helpful to extract data from.


```bash
$ idpbuilder config gitea 
$ idpbuilder config argocd
... 
```

should print the config for a given tool and `-o json` should be available on them too. (output only)


```bash
$ idpbuilder config gitea -o json
```

```json
{
  "url": "https://gitea.cnoe.localtest.me:8443",
  "username": "USERNAME",
  "password": "PASSWORD"
}
```

Given the above, I think `--save` can save the config details for CLI use. 

For gitea it is rather straightforward, as it needs to populate a local git config with the following info

```
[credential "https://gitea.cnoe.localtest.me:8443/"]
        username = [USERNAME]
        password = [PASSWORD]
[http "https://gitea.cnoe.localtest.me:8443/"]
        sslVerify = false
```

For Argo CD, `idpbuilder config argocd --save` should make the credentials available to the argocd CLI.

For Backstage, it will probably be a noop.

I will turn this to an issue and we can discuss there.

**Comment by nimakaviani** [comment]
@cmoulliard I made a more generic proposal under #114. I think we need to do it for all tools. Please comment there with your thoughts.
