### ISSUE TITLE
Use https both internally and externally when using Gitea

### ISSUE THREAD

**Issue by nimakaviani** [cnoe-io/idpbuilder#113]
Right now, the idpbuilder uses the local http connection on port 8880 when interacting with Gitea. This is where both http and https are available for Gitea and we use https over 8443 for all other services (backstage, argo, etc).

We should make it consistent with the rest of the services, and access everything over https. It is fine to use `skipVerify` when configuring the local go client for git in the idpbuilder code to connect to gitea.

**Comment by cmoulliard** [comment]
> Right now, the idpbuilder uses the local http connection on port 8880 when interacting with Gitea. This is where both http and https are available for Gitea and we use https over 8443 for all other services (backstage, argo, etc).

Why is idpbuilder using the ingress external address + port to interact with the internal kubernetes services
```
gitea           my-gitea-http                             ClusterIP   None            <none>        3000/TCP                     46h
gitea           my-gitea-ssh                              NodePort    10.96.11.188    <none>        22:32222/TCP                 46h
```
Logically idp should access it directly using such a convention: 
```
service_name.namespace
service_name.namespace.svc
service_name.namespace.svc.cluster.local
```

**Comment by nimakaviani** [comment]
agreed, not sure why internally we are not using the in-cluster http endpoints. @nabuskey thoughts here?

**Comment by nabuskey** [comment]
`service_name.namespace.svc.cluster.local` will not resolve. Even if it did resolve, it is an IP address in cluster. This is inaccessible from where the controller is running without further translations.

**Comment by nimakaviani** [comment]
gotcha, yeah the controller sits outside the cluster when bootstrapping local packages.
