### ISSUE TITLE
Add security audit to the next release of idpBuilder and onwards

### ISSUE THREAD

**Issue by nimakaviani** [cnoe-io/idpbuilder#135]
As we prepare to do remote cluster deployments via idpBuider, it is required to ensure we do regular security audits as part of cutting the release. 

Let's make it part of the practice and get help from the experts we have available to us at AWS.

**Comment by omrishiv** [comment]
What do you think of some automation for static code analysis/dependency scanning?

**Comment by nimakaviani** [comment]
yeah that would be helpful actually. any particular ones you have in mind?

**Comment by omrishiv** [comment]
https://snyk.io/ is popular and good from what I hear, but we'd need to register an account there. There's also the Github one: https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning. I've also run SonarQube in the past, but we'd either need to self-host it or set it up with them.

**Comment by tapas4java** [comment]
We can take a look at following tools:

1. Trivy (https://trivy.dev/)
2. Grype (https://github.com/anchore/grype)
3. Kubescape (https://kubescape.io)

**Comment by omrishiv** [comment]
> We can take a look at following tools:
> 
> 1. Trivy (https://trivy.dev/)
> 2. Grype (https://github.com/anchore/grype)
> 3. Kubescape (https://kubescape.io)

Nice! https://github.com/aquasecurity/trivy-action

**Comment by nimakaviani** [comment]
is this free?

**Comment by omrishiv** [comment]
https://github.com/marketplace/actions/anchore-container-scan

**Comment by omrishiv** [comment]
> is this free?

Costs the runner fee, which I believe is free for OSS

**Comment by omrishiv** [comment]
Some other actions we may want to include:
https://github.com/marketplace/actions/staticcheck
https://github.com/marketplace/actions/golangci-lint
