### ISSUE TITLE
[Suggestion] Standardize how we install the core components (yaml vs helm charts)

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#14]
## Suggestion

Standardize how we install the core components as currently they are installed using either : 
- A list of kubernetes resources (= Backstage, ingress nginx) or 
- ArgoCD Application (= Crossplane)

As [backstage](https://github.com/backstage/charts) and [ingress](https://github.com/snowdrop/k8s-infra/blob/main/kind/kind.sh#L421-L426) can be installed as Helm charts, I would recommend to follow that approach and to try as much as we can to use a Helm chart. 

Such a helm chart could be deployed as ArgoCD Application CRs. Here is an example to install the [certificate manager](https://github.com/ch007m/my-janus/blob/main/argocd/cert-manager-application.yml#L19-L27) and customize it using values pushed to a git repository. 

Ideally we should even follow this [pattern](https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/#app-of-apps-pattern) `App of Apps pattern` to package in a helm chart containing ArgoCD Application CR what we would like to provision

**Comment by jessesanford** [comment]
I have no problem with standardization and I completely agree that we should at least attempt to consolidate. However I think it's important that we abstract to the best of our ability the underlying package formats and just provide an api for invoking their installation within this project. This issue: https://github.com/cnoe-io/idpbuilder/issues/5 speaks for the need to create a pluggable way of designing "distributions" or "flavors" of IDP stacks and if at all possible I would love for the distro maintainers to be able to choose their own destiny when deciding on what packages to include/how they get transformed into objects that get shipped to the k8s api. Maybe you will have some thoughts on that design? Feel free to comment on that issue. How do you feel about me closing this as duplicate given this context?

**Comment by cmoulliard** [comment]
The issue #5 covers the idea to externalize as a collection of modules in a file, the components to be deployed (backstage, argocd, ingress, crossplane, etc). 

The point that I report here is more about adopting a convention to define how we will define/deploy the different component (backstage, crossplane, cert manager, etc).

As Argocd is a key component of the idpbuilder platform and embeds Helm, then I would be more than happy if we create for each component:
- A Component CR detailing/describing a component to be installed on the platform and a reference to the GVK (GroupVersionKind) about the resource to be deployed
- An ArgoCD application or some ArgoCD applications CRs defining how to deploy the resources of the component: helm (1st choice), yaml resources (2nd choice), etc.
- Link(s) to a git repo containing the config (= helm values) which could be different according to the target platform or hyperscaler's integration
- Jobs (or tasks) to be executed post deployment of the helm chart by ArgoCD
-

**Comment by jessesanford** [comment]
I like all of these thoughts, but I do think that they belong as subordinate part of the overall vision of the package management. I think that we should start with direction we take on how to decouple the apps being installed before we dive into the implementation of how we install them. I am fine with keeping this issue open, but our attention should first be to draft a RFC for the design decisions on #5. @greghaynes @nabuskey @nimakaviani you have any thoughts here?

**Comment by nabuskey** [comment]
I don't think this is relevant anymore. Closing
