### ISSUE TITLE
Ability to get secrets and configmaps

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#150]
When I was porting the reference implementation, I wished there was a way to retrieve all relevant secrets and config map values from the cluster. For example, for the ref implementation, I needed to retrieve values from secrets in two namespaces to log into systems.

What do you think about having a command to get values from secrets and CMs that are labeled in a particular way?

**Comment by cmoulliard** [comment]
> What do you think about having a command to get values from secrets and CMs that are labeled in a particular way?

Why don't we use vault (or alternative) as centralized system to manage for the user(s) their secrets/configs instead of having to query the cluster(s) ?

**Comment by nabuskey** [comment]
fixed in https://github.com/cnoe-io/idpbuilder/pull/193
