### ISSUE TITLE
Do we want to fully support codespaces?

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#152]
GH codespaces is a good way to get started on a project: https://github.com/features/codespaces

It pretty much provisions a VM, then allows you to run w/e on it. You can forward a local port to an external endpoint provided by GH as well.

Having full support for codespaces allows people new to the project to click a button in this project and start playing around with it. I think it's a good way to make it easier for people to get started.

It does come with complications though. See: https://github.com/cnoe-io/idpbuilder/pull/148#issuecomment-1952942333

Is it worthwhile to fully support this? By fully support, I mean allow for users to run this trough their web browsers.

**Comment by nimakaviani** [comment]
certainly very useful and I see this as an easy way to demo and get users excited about the idpbuilder. That said, I dont think this is something we will want to burn cycles from core contributors on at this point. Let's leave it as an open issue, and if there are interested individuals who would want to pick this up, we can support them.
