### ISSUE TITLE
[Bug]: Spark operator not installed in reference-architecture

### ISSUE THREAD

**Issue by allamand** [cnoe-io/idpbuilder#174]
### What is your environment, configuration, and command?

I installed the reference arch in idpbuilder

### What did you do and What did you see instead?

following the default installation path : 

idpbuilder create --use-path-routing --package-dir examples/ref-implementation

In ArgoCD, I can see that there is an error on the Spark operator installation:

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm pull --destination /tmp/4bf70299-a105-4b27-9081-5b29e7bc3c03 --version 1.1.27 --repo https://googlecloudplatform.github.io/spark-on-k8s-operator spark-operator` failed exit status 1: Error: looks like "https://googlecloudplatform.github.io/spark-on-k8s-operator" is not a valid chart repository or cannot be reached: failed to fetch https://googlecloudplatform.github.io/spark-on-k8s-operator/index.yaml : 404 Not Found
```

effectively, this page : https://googlecloudplatform.github.io/spark-on-k8s-operator/index.yaml seems not existing.

### Additional Information. Logs.

```shell
Seems that https://github.com/GoogleCloudPlatform/spark-on-k8s-operator

now redirects on https://github.com/kubeflow/spark-operator
```

**Comment by nimakaviani** [comment]
ah, right! the repo got moved yesterday. Thanks for filing the issue. will have to have it updated.

**Comment by nimakaviani** [comment]
just merged the PR: https://github.com/cnoe-io/idpbuilder/pull/173

closing this issue as the change should fix it

**Comment by allamand** [comment]
Thanks :)
