### ISSUE TITLE
Create new git repository for idpbuilder examples and allow the use of URL for flag -p 

### ISSUE THREAD

**Issue by csantanapr** [cnoe-io/idpbuilder#184]
It would be a good idea to create a git repository with examples that are contributed by the community.

This issue covers two main ideas:
1. Create a new github repo under the cnoe-io github org to create a library of examples that work out of the box with one command. This includes to move out the existing [examples](https://github.com/cnoe-io/idpbuilder/tree/main/examples) directory from the idpbuilder git repo
2. Improve the `idpbuilder` to allow to pass an URL to the `-p` flag

I'm not sure what would be the name of the git repo some thing like `cnoe-examples` or `idpbuilder-examples` or just `examples`

This allows for the community to open issues requesting end to end examples, and for contributors to provide examples.

The user experience should that user should be able to run `idpbuilder` with `-p` and point to an url to deploy the example.
```shell
idpbuilder create -p <URL>
```
The URL format would follow kustomize [URL remote targets](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md#remote-targets)
It would look like this
```shell
idpbuilder create -p https://https://github.com/cnoe-io/examples//ref-implementation
open <backstage-url>
```
This would git clone the files to a tmp directory, and start idpbuilder create -p using the tmp dir

Using the kustomize go-lib then we can support ssh git, timeouts, ref/branches, etc.

For now user would need to git clone and use idpbuilder.
```shell
git clone https://https://github.com/cnoe-io/examples
idpbuilder create -p examples/ref-implementation
```

**Comment by nimakaviani** [comment]
this makes sense to me, thanks. I am also wondering whether we should pull out the existing examples directory and submodule it into the core idpbuilder tool for the existing packages to work out of the box.

**Comment by blakeromano** [comment]
This feels like it should tie in with this proposal -> https://github.com/cnoe-io/proposals/issues/1

**Comment by csantanapr** [comment]
@nimakaviani that's what I was proposing, to move out the existing examples directory from this repo to the new examples git repo
>pull out the existing examples directory

**Comment by nimakaviani** [comment]
sure. I am wondering whether submoduling would be a good way to bring it back in or shall we keep them separate

**Comment by csantanapr** [comment]
Friends don't let friends to submodule, unless the friend will automate the upgrade to the submodule reference

**Comment by nimakaviani** [comment]
haha fair!

**Comment by aatchison** [comment]
I agree with the proposal, I was just thinking about this ⬆️
