### ISSUE TITLE
The secret returned by the command "idpbuilder get secrets" should also include the username for argocd

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#216]
## Feature request

The secret returned by the command "idpbuilder get secrets" should also include the username for argocd as this is the case for "gitea"

```
./idpbuilder get secrets
---------------------------
Name: gitea-admin-secret
Namespace: gitea
Data:
  password : xxxxxxxxxxxx
  username : giteaAdmin
---------------------------
Name: argocd-initial-admin-secret
Namespace: argocd
Data:
  password : xxxxxxxxxxxx
```

**Remark**: The name of the secret (= credential) should be more user friendly. So I suggest to rename :
- `gitea-admin-secret` to `gitea-credential`
- `argocd-initial-admin-secret` to `argocd-credential`

**Comment by nimakaviani** [comment]
yep +1!

**Comment by knottAutodesk** [comment]
plus one too [Slack](https://cloud-native.slack.com/archives/C05TN9WFN5S/p1714076289449349).
