### ISSUE TITLE
use go build ld flags to reduce binary size

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#232]
For releases, I think we can remove debug stuff to reduce the binary size.

This is for releases only. So we just need to modify the go releaser config file: https://github.com/cnoe-io/idpbuilder/blob/64660b389d9e758ce425f5fd3ff9aeca360ae8f2/.goreleaser.yaml#L15-L18

Add the following flags: `-w -s `

**Comment by xoanmm** [comment]
Created [PR](https://github.com/cnoe-io/idpbuilder/pull/275) to solve the mentioned issue
