### ISSUE TITLE
Leverage local docker image cache

### ISSUE THREAD

**Issue by greghaynes** [cnoe-io/idpbuilder#235]
Many of our k8s manifests specify `imagePullPolicy` of always. This includes argocd and gitea which both are sizeable downloads which, as a result of this, are not cached. We should either support setting this as a configuration or change these to `ifNotPresent` so local image caches can be leveraged on slower internet connections.

**Comment by nimakaviani** [comment]
thanks! just PR-ed a fix for it too :)
