### ISSUE TITLE
[Bug]: Cannot pull image from gitea packages

### ISSUE THREAD

**Issue by ricker-flow** [cnoe-io/idpbuilder#243]
### What is your environment, configuration, and command?

idpbuilder 0.4.1 

### What did you do and What did you see instead?

I can push and pull images to Gitea from the commandline. 

```shell
docker push gitea.cnoe.localtest.me:8443/deepsky/digitalasset:latest
```

However, Argo cannot pull the image from Gitea. 

```shell
Failed to pull image "gitea.cnoe.localtest.me:8443/giteaadmin/digitalasset:latest": 
rpc error: code = Unknown desc = failed to pull and unpack image "gitea.cnoe.localtest.me:8443/giteaadmin/digitalasset:latest": 
failed to resolve reference "gitea.cnoe.localtest.me:8443/giteaadmin/digitalasset:latest": 
failed to do request: Head "https://gitea.cnoe.localtest.me:8443/v2/giteaadmin/digitalasset/manifests/latest": 
dial tcp [::1]:8443: connect: connection refused
``` 

Is that the behavior reported with https://github.com/go-gitea/gitea/issues/29591 ?

**Comment by nabuskey** [comment]
This doesn't look like related to the issue linked. Likely because the domain name resolves to 127.0.0.1 inside the cluster. You can work around this by configuring core dns to resolve domain names you are interested in. This is done in the ref implementation example.

I've thinking about making it the default configuration. Any opinions here @nimakaviani @cmoulliard @csantanapr ?

**Comment by nimakaviani** [comment]
yeah, I like the idea of making `cnoe.localtest.me` resolve successfully inside the k8s cluster too.

Not sure if it will lead to anti-patterns though,  eg for folks to experiment with pushing to gitea manually and configuring argo cd apps out of band.

More benefits than harms though, so it is a +1 from me.

**Comment by omrishiv** [comment]
@jessesanford is this closed now from your recent PR?

**Comment by nabuskey** [comment]
This should work now. https://cnoe.io/docs/reference-implementation/installations/idpbuilder/local-oci-registry
Closing this but feel free to re-open
