### ISSUE TITLE
Improve performance by using cached images our deployment definitions specify imagePullPolicy's of always

### ISSUE THREAD

**Issue by csantanapr** [cnoe-io/idpbuilder#244]
From Slack by @greghaynes 
> I notice that a ton of our deployment definitions specify imagePullPolicy's of always which basically invalidates the host cache for kind. What do we think about changing this? If I threw up a PR to change this to IfNotPresent would we be ok with that? Or do we think this needs to be user-settable?

**Comment by nimakaviani** [comment]
This has already been fixed in this PR: https://github.com/cnoe-io/idpbuilder/pull/236

Will become available in the next release. Gotta make sure that we build the latest version of the embedded packages by running  `generate-manifest` before cutting the release.
