### ISSUE TITLE
Feature: Extend `idpbuilder create` command to work with existing k8s cluster

### ISSUE THREAD

**Issue by tapas4java** [cnoe-io/idpbuilder#246]
### Have you searched for this feature request?

- [X] I searched but did not find similar requests

### Problem Statement

`idpbuilder` currently works great for platform engineers to quickly build and test platform stack. But it's not clear how to operationalize the platform on a real k8s cluster from there.

### Possible Solution

I think we should extend `idpbuilder create` command to accept an additional flag and we can skip `kind` cluster creation, instead use existing k8s context to spin up the platform.

**Comment by nimakaviani** [comment]
Thanks for the feature request. yes, definitely on the roadmap and in fact we were discussing this a few days ago.

There is already an issue for it too https://github.com/cnoe-io/idpbuilder/issues/74

I am going to close this as we track all the work on #74
