### ISSUE TITLE
opt-in end-to-end test run for PRs

### ISSUE THREAD

**Issue by rattboi** [cnoe-io/idpbuilder#254]
### Have you searched for this feature request?

- [X] I searched but did not find similar requests

### Problem Statement

New E2E testing is great, but it would be nice to be able to run them for potentially complex PRs prior to merge

### Possible Solution

https://grem1.in/post/gha-comment-trigger/ describes implementing a issue comment trigger for a GHAR workflow for just such cases where you don't want it to be default behavior.

**Comment by rattboi** [comment]
I'm planning to implement this myself

**Comment by nimakaviani** [comment]
thanks, looking forward to the PR!
