### ISSUE TITLE
Bump go version to 1.22

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#259]
To upgrade to k8s 1.30, we need go 1.22
Changes:
- https://github.com/cnoe-io/idpbuilder/blob/1ed542233337eeca121b24a25db5b1e96a722c6d/go.mod#L3
- https://github.com/cnoe-io/idpbuilder/blob/1ed542233337eeca121b24a25db5b1e96a722c6d/.github/workflows/e2e.yaml#L17
- https://github.com/cnoe-io/idpbuilder/blob/1ed542233337eeca121b24a25db5b1e96a722c6d/.github/workflows/pr.yaml#L15
- https://github.com/cnoe-io/idpbuilder/blob/1ed542233337eeca121b24a25db5b1e96a722c6d/.github/workflows/release.yaml#L20

Wonder if we we should store them in repo variables.

**Comment by AryanSharma9917** [comment]
@nabuskey, could you assign this issue to me if no one is working on it? I would like to contribute to it!

**Comment by nabuskey** [comment]
Assigned. Thank you and let me know if you have any questions!
