### ISSUE TITLE
Update k8s to 1.30

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#260]
- [x] #259 
- [ ] Bump https://github.com/cnoe-io/idpbuilder/blob/1ed542233337eeca121b24a25db5b1e96a722c6d/go.mod#L22
- [ ] Bump https://github.com/cnoe-io/idpbuilder/blob/1ed542233337eeca121b24a25db5b1e96a722c6d/go.mod#L17-L20
- [x] Bump https://github.com/cnoe-io/argocd-api/blob/main/go.mod
- [ ] Bump https://github.com/cnoe-io/idpbuilder/blob/f556285d51d7ff00e575cd15c9ecedf0aa5cc409/Makefile#L15
- [x] https://github.com/cnoe-io/idpbuilder/issues/364

Not urgent.

**Comment by AryanSharma9917** [comment]
Hey @nabuskey, can I work on these issues?

**Comment by nabuskey** [comment]
Yes! I think argocd api should be updated first before anything. https://github.com/cnoe-io/argocd-api/blob/main/go.mod

**Comment by AryanSharma9917** [comment]
> Yes! I think argocd api should be updated first before anything. https://github.com/cnoe-io/argocd-api/blob/main/go.mod


Hi @nabuskey , just to confirm: I'll update the Go version in `go.mod` to `go 1.22`, bump the Kubernetes dependencies (`k8s.io/api`, `k8s.io/apiextensions-apiserver`, `k8s.io/apimachinery`, `k8s.io/client-go`) to `v0.30.0`, update `sigs.k8s.io/controller-runtime` to `v0.17.1`, and change `ENVTEST_K8S_VERSION` in the `Makefile` to `1.30.0`. Afterward, I'll run `go mod tidy`. Does this look good? 

---

**Comment by nabuskey** [comment]
> Hi @nabuskey , just to confirm: I'll update the Go version in go.mod to go 1.22, bump the Kubernetes dependencies (k8s.io/api, k8s.io/apiextensions-apiserver, k8s.io/apimachinery, k8s.io/client-go) to v0.30.0, update sigs.k8s.io/controller-runtime to v0.17.1, and change ENVTEST_K8S_VERSION in the Makefile to 1.30.0. Afterward, I'll run go mod tidy. Does this look good?

Yes that makes sense to me. Couple more things we should do that I just noticed: 
- We need to bump https://github.com/cnoe-io/idpbuilder/issues/364 when we bump to v0.30. 
- We need to do the same for argocd api: https://github.com/cnoe-io/argocd-api/issues/4. I'd say this needs to be done first.

Thanks again for working on this!
