### ISSUE TITLE
Enable on cluster resolution of gitea OCI container registry

### ISSUE THREAD

**Issue by jessesanford** [cnoe-io/idpbuilder#282]
Gitea now has implemented my x-forwarded-for fix for the AppURL resolution in 1.22.0. See Discussion here: https://github.com/go-gitea/gitea/issues/29591 and the fix here: https://github.com/go-gitea/gitea/pull/30891 ... while it is not in the release notes for 1.22 you can see that it was merged into that release branch at https://github.com/go-gitea/gitea/commit/d4c2db39bf239d071c6ac96815efa8fd8b03ad94

Let's bump the gitea version to 1.22+ so that we can make use of the oci registry on cluster.

**Comment by nimakaviani** [comment]
PR https://github.com/cnoe-io/idpbuilder/pull/166 partially fixes this.

As part of fully addressing this issue, we should also provide documentation on using the local registry and potentially making use of it where possible.

**Comment by cmoulliard** [comment]
> As part of fully addressing this issue, we should also provide documentation on using the local registry and potentially making use of it where possible.

Is it dlocumented and where ?

**Comment by nimakaviani** [comment]
yes https://cnoe.io/docs/reference-implementation/installations/idpbuilder/local-oci-registry

**Comment by cmoulliard** [comment]
Using v0.6.0, I got a cert error when I perform a `docker login`
```
docker login -u $GITEA_USERNAME -p $GITEA_PASSWORD $GITEA_URL
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to gitea.cnoe.localtest.me failed with status: authenticating creds for "gitea.cnoe.localtest.me": pinging container registry gitea.cnoe.localtest.me: Get "https://gitea.cnoe.localtest.me/v2/": dial tcp 127.0.0.1:443: connect: connection refused
```
Such an error will also take place if a an image is build using a Tekton pipeline and pack CLI
```
[pack-builder : pack] Adding buildpack 'paketo-community/ubi-java-buildpack@0.1.1' (diffID=sha256:c3a9faaa3b63a597a3a5f82b1b2d0ea7cf2c0cc08bdc96e2cfbdedcad5c00d91)
[pack-builder : pack] Adding extension 'paketo-community/ubi-java-extension@0.2.0' (diffID=sha256:ba03dfbb2b9d064b5288afbf4cd330347f393cd6586f0c843ce562e80cc17422)
[pack-builder : pack] Adding extension 'paketo-community/ubi-nodejs-extension@0.3.3' (diffID=sha256:e4f76187731c8ac870316a272902e9e0cfa1c78ca5cb79fe0061f9287649f08d)
[pack-builder : pack] ERROR: failed to write image to the following tags: [gitea.cnoe.localtest.me:8443/giteaadmin/ubi-builder: Get "https://gitea.cnoe.localtest.me:8443/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority]
```
