### ISSUE TITLE
Feature: CoreDNS configuration for core packages

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#300]
### Have you searched for this feature request?

- [X] I searched but did not find similar requests

### Problem Statement

When interacting with core packages like argocd and gitea, the in-cluster DNS name and external (local machine) DNS name may not match out of the box. We work around this by creating a CoreDNS configuration https://github.com/cnoe-io/stacks/blob/main/ref-implementation/coredns/manifests/cm-coredns.yaml in ref impl. 

I don't think we want to do this in external packages. I'd rather take care of these kind of things in idpbuilder itself.

### Possible Solution

Once the cluster is up, we should: 
1. Update the coreDNS CM to use import. https://coredns.io/plugins/import/
2. Enter name resolution information in the referenced file.
3. Wait until name resolves correctly.
This is a one-time operation. We should not do this in case another package overwrites the CM.

**Comment by cmoulliard** [comment]
> 2\. Enter name resolution information in the referenced file.

According to the doc page, the rewrite [rule](https://coredns.io/plugins/rewrite/) should include FROM -> TO but in your example
```
        rewrite name cnoe.localtest.me ingress-nginx-controller.ingress-nginx.svc.cluster.local
```
the incoming names to be resolved including `cnoe.localtest.me` will be rewritten to ` ingress-nginx-controller.ingress-nginx.svc.cluster.local`. Are you sure that the rule is correct ?

**Comment by cmoulliard** [comment]
Is there a way to easily test the rewrite rule post update of the codedns CM ?

**Comment by cmoulliard** [comment]
I did a test where I patched the coreDNS CM 
```
Data
====
Corefile:
----
.:53 {
    errors
    health {
       lameduck 5s
    }
    ready
    rewrite name cnoe.localtest.me ingress-nginx-controller.ingress-nginx.svc.cluster.local
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    prometheus :9153
    forward . /etc/resolv.conf {
       max_concurrent 1000
    }
    cache 30
    loop
    reload
    loadbalance
}
```

of my idpbuilder cluster to include the rewrite rule, restarted the coreDNS deployment and argocd server still complain with the same DNS resolution error when it must create an Application for the git repository -> `http://gitea.cnoe.localtest.me:8443/qshift/my-quarkus-app-job.git`
```
Error creating argo app: application spec for my-quarkus-app-job-bootstrap is invalid: InvalidSpecError: repository not accessible: repositories not accessible: &Repository{Repo: "http://gitea.cnoe.localtest.me:8443/qshift/my-quarkus-app-job.git", Type: "", Name: "", Project: ""}: repo client error while testing repository: rpc error: code = Unknown desc = error testing repository connectivity: Get "http://gitea.cnoe.localtest.me:8443/qshift/my-quarkus-app-job.git/info/refs?service=git-upload-pack": dial tcp 127.0.0.1:8443: connect: connection refused
```

**Comment by cmoulliard** [comment]
If we add to the CM the log parameter, then we can see the DNS records logged when the gitea host FQDN is resolved
```
[INFO] 10.244.0.8:46270 - 38264 "AAAA IN gitea.cnoe.localtest.me.svc.cluster.local. udp 70 false 1232" NXDOMAIN qr,aa,rd 152 0.000110333s
[INFO] 10.244.0.8:55605 - 47160 "AAAA IN gitea.cnoe.localtest.me.cluster.local. udp 66 false 1232" NXDOMAIN qr,aa,rd 148 0.000076375s
[INFO] 10.244.0.8:46066 - 48261 "A IN gitea.cnoe.localtest.me.dns.podman. udp 63 false 1232" NXDOMAIN qr,rd,ra 52 0.000522584s 
[INFO] 10.244.0.8:44104 - 28307 "AAAA IN gitea.cnoe.localtest.me. udp 52 false 1232" NOERROR qr,rd,ra 41 0.001008668s
[INFO] 10.244.0.8:51231 - 60626 "A IN gitea.cnoe.localtest.me. udp 52 false 1232" NOERROR qr,rd,ra 80 0.001741836s
```

**Comment by cmoulliard** [comment]
So you confirm that the `rewrite` rule of the ref implementation was not correct and the good to be used are 
```
        rewrite name gitea.cnoe.localtest.me ingress-nginx-controller.ingress-nginx.svc.cluster.local
        rewrite name cnoe.localtest.me ingress-nginx-controller.ingress-nginx.svc.cluster.local
```

**Comment by cmoulliard** [comment]
> 1. Create a self signed cert

Did you added `alt names` part of the certificate generated ?

**Comment by cmoulliard** [comment]
> If I scaffold a backstage template using the `argocd:create-resources` action, then the resolution looks good except that the port number used is not correct.
> 
> ```
> error testing repository connectivity: Get "http://gitea.cnoe.localtest.me:8443/qshift/my-quarkus-app-job.git/info/refs?service=git-upload-pack
> ": dial tcp 10.244.0.14:8443: connect: connection refused
> ```

Are you sure that your example is working as I got a connection refused except if I change the port from 8443 to 3000 for internal (pod to pod) communication ?

**Comment by nabuskey** [comment]
> So you confirm that the `rewrite` rule of the ref implementation was not correct and the good to be used are 
> 
> ```
> 
>         rewrite name gitea.cnoe.localtest.me ingress-nginx-controller.ingress-nginx.svc.cluster.local
> 
>         rewrite name cnoe.localtest.me ingress-nginx-controller.ingress-nginx.svc.cluster.local
> 
> ```

It is correct for ref implementation because it uses path based routing which means everything is exposed under a single domain name. So we don't need gitea.<domain>.

**Comment by cmoulliard** [comment]
I did a new test without success even if DNS name is well resolved:
```
apiVersion: v1                                                                                        data:                                                                                                   Corefile: |
    .:53 {                                                                                                    errors                                                                                                health {
           lameduck 5s                                                                                        }                                                                                                     ready
                                                                                                              rewrite name gitea.cnoe.localtest.me my-gitea-http.gitea.svc.cluster.local
```
Test
```
 kubectl run -it --rm --restart=Never --image=infoblox/dnstools:latest dnstools
If you don't see a command prompt, try pressing enter.
dnstools# host gitea.cnoe.localtest.me
gitea.cnoe.localtest.me has address 10.244.0.13

BUT 

curl -k https://gitea.cnoe.localtest.me:8443/api/v1/orgs
curl: (7) Failed to connect to gitea.cnoe.localtest.me port 8443: Connection refused
```

**Comment by cmoulliard** [comment]
Sorry. That works. I changed manually the CM but argocd reverted it to the defualt :-) 
New test
```
kubectl run -it --rm --restart=Never --image=infoblox/dnstools:latest dnstools
If you don't see a command prompt, try pressing enter.
dnstools# host gitea.cnoe.localtest.me
gitea.cnoe.localtest.me has address 10.96.60.85
dnstools# curl -k https://gitea.cnoe.localtest.me:8443/api/v1/orgs
[]
```

**Comment by cmoulliard** [comment]
> * Reference it in ingress-nginx. e.g. `--default-ssl-certificate=default/foo-tls`
> 
> * Update argocd-tls-certs-cm with cert.

Can we patch that in a running idpbuilder cluster ? @nabuskey

**Comment by cmoulliard** [comment]
I think that I did what it is needed but `argocd:create-resources` backstage action complains about `tls: failed to verify certificate: x509: certificate signed by unknown authority`

**Comment by nabuskey** [comment]
Something like:

```
apiVersion: v1
data:
  cnoe.localtest.me: |
    -----BEGIN CERTIFICATE-----
    MIIBrzCCAVWgAwIBAgIRAIQj3n3aJFrHGMS0fVUJgiUwCgYIKoZIzj0EAwIwEjEQ
    MA4GA1UEChMHY25vZS5pbzAeFw0yNDA2MTkxNzM2MTlaFw0yNTA2MTkyMzM2MTla
    MBIxEDAOBgNVBAoTB2Nub2UuaW8wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARo
    u/zAIGhxqfP01ozg4MG8ISrGZMy1+6vGlv2V5rvBZF/lcvfJVTKYjz4bXi/rXbvy
    4eIjqMFqJ6r6aKpZNBLjo4GLMIGIMA4GA1UdDwEB/wQEAwIChDATBgNVHSUEDDAK
    BggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTYNT/ktulK/q9c
    ZteIu3lItJti/TAxBgNVHREEKjAoghFjbm9lLmxvY2FsdGVzdC5tZYITKi5jbm9l
    LmxvY2FsdGVzdC5tZTAKBggqhkjOPQQDAgNIADBFAiEAzNHjPgmT83gIJHdxS8Lp
    jrQfiyIfglYxsaB07iiefo8CICY9nIKRoQLz4GqJW+FCrrTFZHqeB9CirFhyHM+9
    EsCc
    -----END CERTIFICATE-----
  gitea.cnoe.localtest.me: |
    -----BEGIN CERTIFICATE-----
    MIIBrzCCAVWgAwIBAgIRAIQj3n3aJFrHGMS0fVUJgiUwCgYIKoZIzj0EAwIwEjEQ
    MA4GA1UEChMHY25vZS5pbzAeFw0yNDA2MTkxNzM2MTlaFw0yNTA2MTkyMzM2MTla
    MBIxEDAOBgNVBAoTB2Nub2UuaW8wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARo
    u/zAIGhxqfP01ozg4MG8ISrGZMy1+6vGlv2V5rvBZF/lcvfJVTKYjz4bXi/rXbvy
    4eIjqMFqJ6r6aKpZNBLjo4GLMIGIMA4GA1UdDwEB/wQEAwIChDATBgNVHSUEDDAK
    BggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTYNT/ktulK/q9c
    ZteIu3lItJti/TAxBgNVHREEKjAoghFjbm9lLmxvY2FsdGVzdC5tZYITKi5jbm9l
    LmxvY2FsdGVzdC5tZTAKBggqhkjOPQQDAgNIADBFAiEAzNHjPgmT83gIJHdxS8Lp
    jrQfiyIfglYxsaB07iiefo8CICY9nIKRoQLz4GqJW+FCrrTFZHqeB9CirFhyHM+9
    EsCc
    -----END CERTIFICATE-----
kind: ConfigMap
```

The certificate differs between installations obviously.

**Comment by cmoulliard** [comment]
> The certificate differs between installations obviously.

Is the certificate you generate signed by a well-know authority otherwise you will get like me a `signed by unknown authority` ?
