### ISSUE TITLE
Extend the 'idpbuilder get secrets' command to display credentials for the Argo Workflow instance

### ISSUE THREAD

**Issue by gauravhub** [cnoe-io/idpbuilder#361]
Currently, 'idpbuilder get secrets' display credentials for backstage and ArgoCD instances. Extend the 'idpbuilder get secrets' command to display credentials for the Argo Workflow instance as well.

**Comment by nabuskey** [comment]
Not sure what credentials we can pull currently other than the appropriately labeled secrets. Argo Workflows isn't a core package so I am very hesitant to introduce something like this for a particular technology.

**Comment by nimakaviani** [comment]
hmmm, isnt it that Argo Workflow should have the necessary SSO configurations in place so that it also authenticates via keycloak?

**Comment by nabuskey** [comment]
Closing this since we don't ship Argo Workflows with idpbuilder.
