### ISSUE TITLE
[Bug]: Kind cannot pull container images from gitea when using path based routing

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#410]
### What is your environment, configuration, and command?

when the ` --use-path-routing` flag is used, the kind config needs to match like so:

```yaml
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."cnoe.localtest.me:8443"]
    endpoint = ["https://cnoe.localtest.me"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."cnoe.localtest.me".tls]
    insecure_skip_verify = true
```

Otherwise, the kind cluster cannot pull images references by pods.

### What did you do and What did you see instead?

Could not pull images

**Comment by mouuii** [comment]
can you  add some ref to explain this problem ?
