### ISSUE TITLE
[Bug]: install err context calcel

### ISSUE THREAD

**Issue by mouuii** [cnoe-io/idpbuilder#413]
### What is your environment, configuration, and command?

when i run idpbuild create on unbuntu vm ,  i can not know where i fail , only log checking if we should shutdown.....

### What did you do and What did you see instead?

d

### Additional Information. Logs.

![1729057622135](https://github.com/user-attachments/assets/465cb087-c979-4470-9109-fc8ddedf4347)

**Comment by nabuskey** [comment]
Hmm not sure what went wrong there. I develop on Ubuntu and it works well for me.
 idpbuilder supports outputting more verbose output with the `-l` flag. For debug output, try passing `-l debug` and see if you can see what went wrong.

**Comment by mouuii** [comment]
After a while, it's okay. Next time I create it, I will try turning on debug.
