### ISSUE TITLE
ArgoCD crossplane application fails to be deployed as it uses a wrong Argocd project name

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#42]
## Issue

The ArgoCD crossplane application fails to be deployed as it refers to a wrong project name. Name should be: `idpbuilder-local-gitserver` and not `idpbuilder-embedded-gitserver`

![Screenshot 2023-10-18 at 11 26 08](https://github.com/cnoe-io/idpbuilder/assets/463790/f57101e7-8214-47b2-81ba-6fcc48cda7f6)

**Comment by nimakaviani** [comment]
hmmm, the default value for `buildName` is `localdev` actually and not `local` as seen here:

https://github.com/cnoe-io/idpbuilder/blob/ff13799770d100f043c528c84e4739e68ccbe667/pkg/cmd/create/root.go#L34

so, the current fix in #43 still won't work unless users explicitly pass `--buildName=local`.

i suggest we remove the `--buildName` flag from the `create` command and just default the `buildName` to `local` for the first release so things work as expected. Given that the idpbuilder only launches a local idp, this should work fine conceptually. 

Also, do we see any particular value in having a configurable buildName?

**Comment by cmoulliard** [comment]
> Separately though, do we see any particular value in having a configurable buildName?

Such a "build name" is also used as the name to configure the kind cluster to be deleted/created. See here: https://github.com/cnoe-io/idpbuilder/blob/main/pkg/kind/cluster.go#L81 or https://github.com/cnoe-io/idpbuilder/blob/main/pkg/kind/cluster.go#L95. 
So, if a user is interested to create several kind clusters, than such a name is relevant but less from the build (or IDP creation) point of view but more to have x kind clusters

**Comment by cmoulliard** [comment]
As my pr has been merged, I suggest to close this issue but that we create another one or several to:
- Rename `buildName` parameter to `clusterName` or simply `name` as it should be used only to name the cluster and not by example used part of the command `gitserver create --buildName` 
- Review how we name the namespace, image tag, etc

**Comment by nimakaviani** [comment]
problem is the PR doesnt fix the issue unless we change the default value for `--buildName` to `local`. thats one way to go about it but things break if people set a different name. that's why I am suggesting the alternative approaches.

Also, this needs fixing before we cut a release.

**Comment by nabuskey** [comment]
https://github.com/cnoe-io/idpbuilder/pull/43#issuecomment-1769012891

I suggest use the default project for this release. 

> Rename buildName parameter to clusterName or simply name as it should be used only to name the cluster and not by example used part of the command gitserver create --buildName

I also agree with this.

**Comment by greghaynes** [comment]
I like this idea. Build name is a leftover from when this whole thing was in ideation - it makes sense to only support one "build" per cluster as all the CRDs and many of the controllers we're installing are singleton.
