### ISSUE TITLE
shorten the base host names for the deployed services

### ISSUE THREAD

**Issue by nimakaviani** [cnoe-io/idpbuilder#47]
As per [this slack conversation](https://cloud-native.slack.com/archives/C05TN9WFN5S/p1697645158288909?thread_ts=1697611323.863679&cid=C05TN9WFN5S) let's change all host names from `*.idpbuilder.cnoe.io.localtest.me` to `*.cnoe.localtest.me`

**Comment by kahilof** [comment]
@nimakaviani @nabuskey https://github.com/cnoe-io/idpbuilder/pull/55
