### ISSUE TITLE
Make it possible for people to use a different Backstage image when starting the idpbuilder

### ISSUE THREAD

**Issue by nimakaviani** [cnoe-io/idpbuilder#51]
Based on this slack conversation

```
Charles Moulliard:
As the purpose of idpbuilder is to let a user to setup their own IDP (= to use their backstage packaging = plugins, etc), then we should at least before to release idpbuilder to allow to have a parameter able to set the backstage image to be used as the imageTag is hardCoded:
```
https://github.com/cnoe-io/idpbuilder/blob/1859b59123820aa326ddc983779c678f879ac2ea/pkg/apps/srv/backstage/install.yaml#L98

few considerations here:

- it will make it harder to ship the idpbuilder with preconfigured plugins and assume certain workflows as things may break when a custom image is used
- it introduces a dependency to an external OCI registry to pull the image from

**Comment by cmoulliard** [comment]
> * it introduces a dependency to an external OCI registry to pull the image from

This is also the same for all the components deployed on the idp platform by argocd (or kind too) as they are consuming images from external repositories (docker, gcr, etc)

**Comment by cmoulliard** [comment]
> * it will make it harder to ship the idpbuilder with preconfigured plugins and assume certain workflows as things may break when a custom image is used

I dont think so. If we support, part of the idpbuilder tool (= pluggable packages and its configuration), a way to map a backstage plugin to a pluggable component to be deployed by the idpbuilder, then you will be able to resolve this problem which is today not at all manageg by the existing IDP that I'm aware: Tanzu TAP, Red Hat Developer Hub, etc 

Example for sonarqube
`Backastage node package: "@backstage/plugin-sonarqube": "0.7.5" which corresponds to a helm `helm upgrade --install -n sonarqube sonarqube sonarqube/sonarqube` chart that we could bind to an ArgoCD Application CR

**Comment by nabuskey** [comment]
We do not ship backstage with the binary anymore. This issue can be closed.
