### ISSUE TITLE
[Bug]: Wrong kind kube version defined as default

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#68]
### What is your environment, configuration, and command?

OS: Macos

## Issue

When we build using the main branch idpbuilder and use it to create a kind cluster
```
./idpbuilder create --buildName local --recreate --zap-encoder console 
```
then, we got this error: `failed to pull image "kindest/node:v1.26.333": command "docker pull kindest/node:v1.26.333" failed with error: exit status 1` as the default kind kubernetes version is wrong: `v1.26.6`. 

The default value should be `v1.26.6` or one published here according to the kind version - https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0

**Comment by nabuskey** [comment]
I noticed it too and I've fixed this in https://github.com/cnoe-io/idpbuilder/pull/64/files

Looks like the default flag value wasn't correct.

**Comment by nimakaviani** [comment]
yeah this is fixed. closing.
