### ISSUE TITLE
Support non-docker providers

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#85]
Currently the only kind provider supported is Docker. This could be troublesome for some organizations that do not allow Docker usages on developers' laptops due to licensing issues. Kind supports podman as an alternative for Docker. In my experience, it works well. We should support podman and other future providers. 

Currently we use the docker provider as specified here: https://github.com/cnoe-io/idpbuilder/blob/458852cae89657eea8f54d94b156f46e61f5397c/pkg/kind/cluster.go#L94

The logic to enable podman in kind is set via the env var set here: 
https://github.com/kubernetes-sigs/kind/blob/a4bcc7b382d6f2d4fc8d83d6d8ce0c2d44ce2419/pkg/internal/runtime/runtime.go#L11

Unfortunately this is an internal package so we will probably have to implement our own. But we should follow the same pattern.

**Comment by cmoulliard** [comment]
> Unfortunately this is an internal package so we will probably have to implement our own. But we should follow the same pattern.

Are you sure. Maybe using such functions could help us https://github.com/kubernetes-sigs/kind/blob/a4bcc7b382d6f2d4fc8d83d6d8ce0c2d44ce2419/pkg/cluster/provider.go#L157-L167 ?

**Comment by nabuskey** [comment]
> > Unfortunately this is an internal package so we will probably have to implement our own. But we should follow the same pattern.
> 
> Are you sure. Maybe using such functions could help us https://github.com/kubernetes-sigs/kind/blob/a4bcc7b382d6f2d4fc8d83d6d8ce0c2d44ce2419/pkg/cluster/provider.go#L157-L167 ?

The provider themselves are exported. What I meant to say is the logic to enable other providers is not exported. So we will either have to match the logic or come up with other configuration methods.
