### ISSUE TITLE
Consider removing unnecessary ArgoCD pods 

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#86]
We should consider minimizing the pods we install by default to minimize resource usages.  ArgoCD installation creates pods we probably won't use for local development purposes.

```yaml
argocd               argocd-application-controller-0                     1/1     Running     0          3m23s
argocd               argocd-applicationset-controller-5449b5bb46-84grr   1/1     Running     0          3m23s
argocd               argocd-dex-server-587966b5d6-p7b46                  1/1     Running     0          3m23s
argocd               argocd-notifications-controller-5666969f49-mdrm6    1/1     Running     0          3m23s
argocd               argocd-redis-7d8d46cc7f-lzthx                       1/1     Running     0          3m23s
argocd               argocd-repo-server-7c58f4b8d8-7925h                 1/1     Running     0          3m23s
argocd               argocd-server-6c4776b9bb-89rpf                      1/1     Running     0          3m23s
```

Consider removing dex and notification controllers.

**Comment by morey-tech** [comment]
I'm interested in helping with this issue, but I'm having trouble locating where the resources to install Argo CD are defined. Can you point me in the right direction?

**Comment by morey-tech** [comment]
What is the plan for maintaining the `install.yaml` file if we alter it from what is provided in `argoproj/argo-cd`? I figure there are three options for making this change:

1. Simply remove the resources relating to dex and the notification controller (e.g. Deployments, ServiceAcconts, Services, etc).
2. Create a script in `hack/` to use the base in `argoproj/argocd` and remove the resources with a kustomize patch or use Helm to template with and disable these parts (if the option is available).
3. Add support to the `idpbuilder` to use kustomize (or helm) when deploying to the cluster.

1 and 2 I can do with little support, 3 I would need some more direction for where to start in the codebase.

**Comment by nabuskey** [comment]
Option 2 sounds great to me. Create a script in `hack/`. This script should  use kustomize and reference the remote kustomize bases with a specific tag `v2.9.2`.  Probably makes more sense to add to core install than to remove from full install. But I haven't looked into how exactly these manifests are generated in ArgoCD so you may know more. 

Honestly, I wasn't expecting creating scripts for this particular issue. But if you are comfortable with it, I am all for it.

**Comment by cmoulliard** [comment]
There is a better option which is to disable the non needed argocd components using the `enable` boolean:
- Dex: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L877
- Notification: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L2766

**Comment by morey-tech** [comment]
@cmoulliard, the project maintains plain manifests for the Argo CD install and is not using Helm. So, it's not as simple as using the `enable` boolean. However, the script I added to `hack/` to generate these manifests could take advantage of Helm. I'm leaning towards `kustomize` since it's more native to K8s, and we won't see much benefit from the Helm abstraction, but that's my bias.

**Comment by nabuskey** [comment]
I agree with using kustomize here since it is closer to native k8s and ArgoCD project seems to use it to generate manifests for end users.

**Comment by nimakaviani** [comment]
hey @morey-tech ... not sure if I have seen any activity in relation to the script you have added to `hack/`. Can you please finalize and push the PR to close this? or let us know if your priorities have changed and we need to take this on. thanks!

**Comment by morey-tech** [comment]
@nimakaviani, thanks for the nudge! Published the PR: https://github.com/cnoe-io/idpbuilder/pull/122

**Comment by nimakaviani** [comment]
Thank you @morey-tech !
