### ISSUE TITLE
Print instructions on how to access ArgoCD UI

### ISSUE THREAD

**Issue by nabuskey** [cnoe-io/idpbuilder#92]
We can improve user experience of using ArgoCD by making it easier for users to get the default admin credentials. 

We can either print the ArgoCD admin password to stdout or print the instructions on how to get the password e.g. `kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d` 

Whenever I spin up a new cluster, I have to search the command history to get the password and it gets a bit too annoying for me.

**Comment by nimakaviani** [comment]
good idea!

**Comment by cmoulliard** [comment]
Ideally we should get such information using the `idp` client and new commands:
```
./idpbuilder package list
./idpbuilder package show argocd
url: https://argocd.127.0.0.1.nip.io
user: admin
pwd: <password>
etc
./idpbuilder package show gitea
url: https://gitea.127.0.0.1.nip.io
user: admin
pwd: <password>
etc
```
